import Foundation
import OpenCountShared
// OpenCountShared is the KMP framework generated by packages/shared
// Build: ../gradlew :packages:shared:linkDebugFrameworkIosSimulatorArm64
// Integration: Add OpenCountShared.framework to Xcode project

/// Bridge between SwiftUI and KMP shared module
enum KMPBridge {
    static func greet() -> String {
        return "OpenCount SDK v\(OpenCountSDK.shared.VERSION) on \(Platform_iosKt.getPlatformName())"
    }
}
